spring.application.name=demo

spring.datasource.url = jdbc:postgresql://localhost:5432/mydb
spring.datasource.username = postgres
spring.datasource.password = GonFreecss405

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true